# Generated by Django 5.2.7 on 2025-10-23 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Elan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100, verbose_name='Məhsulun adı')),
                ('qiymet', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Qiymət (AZN)')),
                ('tarix', models.DateField(auto_now_add=True, verbose_name='Tarix')),
                ('shekil', models.ImageField(upload_to='elanlar/', verbose_name='Şəkil')),
                ('melumat', models.TextField(blank=True, null=True, verbose_name='Qısa məlumat')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=150, verbose_name='İstifadəçi adı')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email ünvanı')),
                ('shekil', models.ImageField(blank=True, null=True, upload_to='profil/', verbose_name='Profil şəkli')),
            ],
        ),
    ]
