# Generated by Django 5.2.7 on 2025-10-23 20:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='Bio')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profil_shekilləri/', verbose_name='Profil şəkli')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Elan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100, verbose_name='Məhsulun adı')),
                ('qiymet', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Qiymət (AZN)')),
                ('tarix', models.DateField(auto_now_add=True, verbose_name='Tarix')),
                ('shekil', models.ImageField(upload_to='elanlar/', verbose_name='Şəkil')),
                ('melumat', models.TextField(blank=True, null=True, verbose_name='Qısa məlumat')),
                ('istifadeci', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kentci.userprofile')),
            ],
        ),
    ]
