# Generated by Django 5.2.7 on 2025-10-23 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kentci', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='shekil',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name='Bio'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profil_shekilləri/', verbose_name='Profil şəkli'),
        ),
    ]
